version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/code_pipeline_test
hooks:
  BeforeInstall:
    - location: scripts/remove_old
      timeout: 5800
      runas: root
  AfterInstall:
    - location: scripts/bundle_install
      timeout: 5800
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 5800
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
